### ISSUE TITLE
How to make subscribe form and send a news?

### ISSUE THREAD

**Issue by tersosufix** [robgnu/grav-plugin-subscriber#7]
Hi. Just can't get how to add a form which will send a user data like e-mail from the form on the page to (un)subscribe and other thing is - if this plugin found that this e-mail address was already used then it will unsubscribe users, or just how to add another link which also be able to take users e-mail from form.
Now i'm using form like this:
title: Рассылка
child_type: default
process:
    markdown: true
    twig: true
robots:
    noindex: false
    nofollow: false
---------------------
```
<form id="newsletter-signup" action="https://stl48.ru/newsletter?action=unsubscribe&email={{form.value.email }}" method="post">
<fieldset>
<label for="signup-email">Подпишитесь на рассылку по e-mail новостей, предложений и событий:</label>
<input type="text" name="email" id="email" /><br />
<input type="submit" id="signup-button" value="Подписаться!" />
<p id="signup-response"></p>
</fieldset>
</form>
{{ subscriber() }}

```
But i guess this is not the way how it's work coz it doesn't work.
I even ready to pay money to make subscription on my site. Anybody can help me?

**Comment by jeffmcneill** [comment]
The way to do this is to make the Newsletter page a FORM type. Then have the form use this kind of metadata:

```
title: Newsletter
never_cache_twig: true
cache_enable: false
form:
    name: Subscription
    fields:
        -
            name: action
            type: radio
            label: Choice
            default: subscribe
            options:
                subscribe: Subscribe
                unsubscribe: Unsubscribe
            validate:
                required: true
        -
            name: email
            label: Email
            placeholder: 'Enter your email address'
            type: email
            validate:
                required: true
    buttons:
        -
            type: submit
            value: Submit
        -
            type: reset
            value: Reset
    process:
        -
            redirect: '/newsletter?action={{ form.value.action }}&email={{ form.value.email }}'
```

The content for the page itself should still have: 

`{{ subscriber() }}`

And some other text to help introduce the form. 

Works a charm.
